Feat/ feature editing
Lowgular/features pull request #12
Opened 2022-07-20 15:33 UTC by Ramotka

2022-07-21 14:09 UTC, gradzio requested changes

2022-07-21 14:09 UTC, gradzio commented on projects/feature/src/lib/adapters/primary/components/edit-feature.component.ts
> +    @Inject(SELECTS_FEATURE_ID_CONTEXT)
you should not have access to neither DTO nor Context Ports in component. If you use state, you should be consistent and use state all the way. So please Move these dependencies into state and use Commands and Querries

2022-07-21 14:09 UTC, gradzio commented on projects/feature/src/lib/adapters/primary/components/feature-list.component.html
> +    <!-- <div class="flex justify-between"> -->
Please no comments in final PR :)

2022-07-21 14:09 UTC, gradzio commented on projects/feature/src/lib/adapters/primary/resolvers/feature-id.resolver.ts
> +    @Inject(SETS_STATE_FEATURE_ID_CONTEXT)
You should use Command Port here

2022-07-22 10:55 UTC, Ramotka commented on projects/feature/src/lib/adapters/primary/components/edit-feature.component.ts
> +    @Inject(SELECTS_FEATURE_ID_CONTEXT)
fixed in the following commits

2022-07-22 10:55 UTC, Ramotka commented on projects/feature/src/lib/adapters/primary/components/feature-list.component.html
> +    <!-- <div class="flex justify-between"> -->
ok :)

2022-07-22 10:55 UTC, Ramotka commented on projects/feature/src/lib/adapters/primary/resolvers/feature-id.resolver.ts
> +    @Inject(SETS_STATE_FEATURE_ID_CONTEXT)
fixed in the following commits

2022-07-22 19:58 UTC, merged