Feat/login
Lowgular/features pull request #16
Opened 2022-07-23 21:03 UTC by Ramotka

2022-07-24 09:03 UTC, gradzio requested changes

2022-07-24 09:03 UTC, gradzio commented on projects/user-auth/src/lib/adapters/primary/components/login.component.ts
> +        tap((data) => localStorage.setItem('accessToken', data.accessToken)),
Local storage should be part of the storage used behind the context port

2022-07-24 09:03 UTC, gradzio commented on projects/user-auth/src/lib/adapters/primary/components/login.component.html
> +      <mat-icon matSuffix (click)="hide = !hide">{{
I personally don't like template vars. Please make It part of the component. You can use behavior subject

2022-07-24 13:02 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/primary/components/login.component.html
> +      <mat-icon matSuffix (click)="hide = !hide">{{
Logic moved to component. For now a simpler version without the behavior subject :)

2022-07-24 13:02 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/primary/resolvers/current-user-id.resolver.ts
> +export class CurrentUserIdResolver implements Resolve<boolean> {
No :)

2022-07-24 13:02 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/primary/guards/auth.guard.ts
> +export class AuthGuard implements CanActivate {
fixed in the next commit

2022-07-24 13:03 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/secondary/services/http-auth.service.ts
> +      .post<any>(
Fixed in the next commit

2022-07-24 13:03 UTC, Ramotka commented on projects/user-auth/src/lib/application/ports/secondary/dto/response.dto.ts
> +export interface ResponseDTO {
Fixed in the next commit

2022-07-24 13:11 UTC, Ramotka commented on src/app/pages/home.page-module.ts
> +        canActivate: [AuthGuard],
Fixed in the next commit

2022-07-24 13:27 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/primary/guards/auth.guard.ts
> +    if (localStorage.length === 0) {
I'm not sure how to do this

2022-07-24 13:27 UTC, Ramotka commented on projects/user-auth/src/lib/adapters/primary/components/login.component.ts
> +        tap((data) => localStorage.setItem('accessToken', data.accessToken)),
I'm not sure how to do this

2022-07-24 18:35 UTC, gradzio requested changes

2022-07-24 18:35 UTC, gradzio commented on projects/user-auth/src/lib/adapters/primary/components/login.component.ts
> +  hideVisibilityIcon: boolean = true;
We should have only observable in smart components. Please use behavior subject instead

2022-07-24 18:35 UTC, gradzio commented on projects/user-auth/src/lib/application/ports/secondary/context/selects-local-storage.context-port.ts
> +  isLoggedIn(): Observable<boolean>;
This should be select

2022-07-24 18:35 UTC, gradzio commented on projects/user-auth/src/lib/application/ports/secondary/context/selects-local-storage.context-port.ts
> +export const SELECTS_LOCAL_STORAGE_CONTEXT =
You should not have local storage in port name. It is abstracting away from infra detail. Just call it token storage

2022-07-24 18:35 UTC, gradzio commented on projects/user-auth/src/lib/application/ports/secondary/context/sets-state-local-storage.context-port.ts
> +export const SETS_STATE_LOCAL_STORAGE_CONTEXT =
Same here sets state token context

2022-07-24 18:35 UTC, gradzio commented on projects/user-auth/src/lib/application/ports/secondary/context/sets-state-local-storage.context-port.ts
> +  setLocalStorage(key: string, value: string): void;
SetState

2022-07-25 14:23 UTC, gradzio approved these changes

2022-07-25 15:42 UTC, merged