Feat/ current user id stored in local storage
Lowgular/features pull request #20
Opened 2022-07-27 16:51 UTC by Ramotka

2022-07-28 13:25 UTC, gradzio requested changes

2022-07-28 13:25 UTC, gradzio commented on projects/feature/src/lib/adapters/primary/components/feature-list.component.ts
> +      .subscribe();
you must not subscribe inside a tap, please remove .subscribe() and change tap() for switchMap() and it will work in reactive way

2022-07-28 13:25 UTC, gradzio commented on projects/feature/src/lib/application/ports/secondary/dto/feature.dto.ts
> +  readonly creator: string | null;
it should not be possible to not have a creator, so please keep it a string

2022-07-28 13:25 UTC, gradzio commented on projects/shared/src/lib/adapters/secondary/storages/current-user.storage.ts
> +    return of(localStorage.setItem(key, value));
it would be better if localStorage is injected via constructor

2022-07-29 14:05 UTC, Ramotka commented on projects/feature/src/lib/adapters/primary/components/feature-list.component.ts
> +      .subscribe();
fixed

2022-07-29 14:05 UTC, Ramotka commented on projects/feature/src/lib/application/ports/secondary/dto/feature.dto.ts
> +  readonly creator: string | null;
fixed

2022-07-29 14:05 UTC, Ramotka commented on projects/shared/src/lib/adapters/secondary/storages/current-user.storage.ts
> +    return of(localStorage.setItem(key, value));
fixed

2022-07-29 14:11 UTC, merged