Feat/ create new feature
Lowgular/features pull request #7
Opened 2022-07-15 15:41 UTC by Ramotka

2022-07-15 18:31 UTC, gradzio requested changes

2022-07-15 18:31 UTC, gradzio commented on projects/feature/src/lib/application/ports/secondary/dto/feature.dto.ts
> +  readonly voters: string[];
Should be set to avoid duplucates

2022-07-15 18:31 UTC, gradzio commented on projects/feature/src/lib/application/state/features.state.ts
> +    return this._addsFeatureDto.add({
If you use state. Then you should save it in storage via context port

2022-07-15 18:31 UTC, gradzio commented on projects/feature/src/lib/application/ports/primary/command/add-feature.command.ts
> +export class AddFeatureCommand {
This name is confusing with dto port. Please rename it to: CreateFeatureCommand. The same with command port

2022-07-16 10:19 UTC, Ramotka commented on projects/feature/src/lib/application/ports/primary/command/add-feature.command.ts
> +export class AddFeatureCommand {
Command renamed in the following commit

2022-07-16 10:20 UTC, Ramotka commented on projects/feature/src/lib/application/state/features.state.ts
> +    return this._addsFeatureDto.add({
featureContext and storage used in state in the following commit

2022-07-16 10:27 UTC, Ramotka commented on projects/feature/src/lib/application/ports/secondary/dto/feature.dto.ts
> +  readonly voters: string[];
DTO changed in the following commit

2022-07-17 13:17 UTC, gradzio approved these changes

2022-07-17 13:17 UTC, merged